# -*- coding: utf-8 -*-
#
# This file is part of INSPIRE.
# Copyright (C) 2014-2017 CERN.
#
# INSPIRE is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# INSPIRE is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with INSPIRE. If not, see <http://www.gnu.org/licenses/>.
#
# In applying this license, CERN does not waive the privileges and immunities
# granted to it by virtue of its status as an Intergovernmental Organization
# or submit itself to any jurisdiction.

version: '2.1'

services:
  test-service_base:
    # Overrides default inspirehep config.
    extends:
      file: services.yml
      service: base
    environment:
      - APP_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://inspirehep:dbpass123@test-database:5432/inspirehep
      - APP_CELERY_BROKER_URL=pyamqp://guest:guest@test-rabbitmq:5672//
      - APP_CELERY_RESULT_BACKEND=redis://test-redis:6379/1
      - APP_CACHE_REDIS_URL=redis://test-redis:6379/0
      - APP_ACCOUNTS_SESSION_REDIS_URL=redis://test-redis:6379/2
      - APP_SEARCH_ELASTIC_HOSTS=test-indexer


  unit:
    extends:
      service: test-service_base
    volumes_from:
      - test-static
    command: bash -c "flake8 inspirehep tests && py.test tests/unit && make -C docs html"

  workflows:
    extends:
      service: test-service_base
    command: py.test tests/integration/workflows
    volumes_from:
      - test-static
    depends_on:
      test-database:
        condition: service_healthy
      test-indexer:
        condition: service_healthy
      test-redis:
        condition: service_healthy

  integration:
    extends:
      service: test-service_base
    command: py.test tests/integration --ignore tests/integration/workflows
    volumes_from:
      - test-static
    depends_on:
      test-database:
        condition: service_healthy
      test-indexer:
        condition: service_healthy
      test-redis:
        condition: service_healthy

  ui:
    extends:
      service: test-service_base
    command: py.test --driver Remote --host selenium --port 4444 --capability browserName firefox --html=selenium-report.html tests/ui
    volumes_from:
      - test-static
    depends_on:
      test-database:
        condition: service_healthy
      test-indexer:
        condition: service_healthy
      test-rabbitmq:
        condition: service_healthy
      test-redis:
        condition: service_healthy
      test-worker:
        condition: service_healthy
      selenium:
        condition: service_started
      test-web:
        condition: service_started
    environment:
      - SERVER_NAME=test-web:5000

  visible_ui:
    extends:
      service: test-service_base
    command: py.test --driver Firefox --host selenium --port 4444 --capability browserName firefox --html=selenium-report.html tests/ui
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    volumes_from:
      - test-static
    depends_on:
      test-database:
        condition: service_healthy
      test-indexer:
        condition: service_healthy
      test-rabbitmq:
        condition: service_healthy
      test-redis:
        condition: service_healthy
      test-worker:
        condition: service_healthy
      selenium:
        condition: service_started
      test-web:
        condition: service_started
    environment:
      - SERVER_NAME=test-web:5000
      - DISPLAY=$DISPLAY

  ui-authors:
    extends:
      service: test-service_base
    command: py.test --driver Remote --host selenium --port 4444 --capability browserName firefox --html=selenium-report.html tests/ui/authors
    volumes_from:
      - test-static
    depends_on:
      test-database:
        condition: service_healthy
      test-indexer:
        condition: service_healthy
      test-rabbitmq:
        condition: service_healthy
      test-redis:
        condition: service_healthy
      test-worker:
        condition: service_healthy
      selenium:
        condition: service_started
      test-web:
        condition: service_started
    environment:
      - SERVER_NAME=test-web:5000

  ui-literature:
    extends:
      service: test-service_base
    command: py.test --driver Remote --host selenium --port 4444 --capability browserName firefox --html=selenium-report.html tests/ui/literature
    volumes_from:
      - test-static
    depends_on:
      test-database:
        condition: service_healthy
      test-indexer:
        condition: service_healthy
      test-rabbitmq:
        condition: service_healthy
      test-redis:
        condition: service_healthy
      test-worker:
        condition: service_healthy
      selenium:
        condition: service_started
      test-web:
        condition: service_started
    environment:
      - SERVER_NAME=test-web:5000

  test-web:
    extends:
      service: test-service_base
    command: gunicorn -b 0.0.0.0:5000 -t 3600 -w 1 --access-logfile "-" inspirehep.wsgi_with_coverage:application
    volumes_from:
      - test-static
    depends_on:
      test-database:
        condition: service_healthy
      test-indexer:
        condition: service_healthy
      test-rabbitmq:
        condition: service_healthy
      test-redis:
        condition: service_healthy
    environment:
      - APP_SERVER_NAME=test-web:5000

  test-worker:
    extends:
      service: test-service_base
    command: celery worker -E -A inspirehep.celery_tests --loglevel=INFO --purge --queues celery,migrator,harvests,orcid_push
    volumes_from:
      - test-static
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD"
        - "bash"
        - "-c"
        - "/virtualenv/bin/celery --broker=pyamqp://guest:guest@test-rabbitmq:5672// inspect ping | grep OK"
    depends_on:
      test-database:
        condition: service_healthy
      test-indexer:
        condition: service_healthy
      test-rabbitmq:
        condition: service_healthy
      test-redis:
        condition: service_healthy

  test-redis:
    image: redis:3.2.3
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD"
        - "bash"
        - "-c"
        - "exec 3<> /dev/tcp/127.0.0.1/6379 && echo PING >&3 && head -1 <&3 | grep PONG"

  test-indexer:
    extends:
      file: services.yml
      service: indexer
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD-SHELL"
        - "curl http://localhost:9200/_cluster/health | grep '.status.:.\\(green\\|yellow\\)'"

  test-rabbitmq:
    image: rabbitmq
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD"
        - "rabbitmqctl"
        - "status"

  test-database:
    extends:
      file: services.yml
      service: database
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD-SHELL"
        - "pg_isready --dbname=inspirehep --host=localhost --username=inspirehep"

  selenium:
    image: selenium/standalone-firefox:2.53.1-beryllium

  test-static:
    extends:
      file: services.yml
      service: static

      # Service for mocking external services.
  fake-arxiv:
    extends:
      service: test-service_base
    ports:
      - "8888:5000"
    command: gunicorn -b 0.0.0.0:8888 -t 3600 --access-logfile "-" --reload inspirehep.testlib.fake_arxiv_service
    volumes_from:
      - test-static

  fake-legacy:
    extends:
      service: test-service_base
    ports:
      - "6666:5000"
    command: gunicorn -b 0.0.0.0:6666 -t 3600 --access-logfile "-" --reload inspirehep.testlib.fake_legacy_service
    volumes_from:
      - test-static

  test-scrapyd:
    extends:
      service: test-service_base
    command: bash -c "rm -f twistd.pid && exec scrapyd"
    volumes_from:
      - test-static
    environment:
      - APP_FILES_STORE=/tmp/file_urls
      - APP_LAST_RUNS_PATH=/code/.scrapy/last_runs
      - APP_CRAWL_ONCE_PATH=/code/.scrapy
      - APP_BROKER_URL=pyamqp://guest:guest@test-rabbitmq:5672//
      - APP_CELERY_RESULT_BACKEND=redis://test-redis:6379/1
    depends_on:
      test-rabbitmq:
        condition: service_healthy
      test-redis:
        condition: service_healthy

  test-scrapyd-deploy:
    extends:
      service: test-service_base
    working_dir: /virtualenv/lib/python2.7/site-packages/hepcrawl
    command: bash -c "sed -i -e 's|^url .*|url = http://test-scrapyd:6800|' scrapy.cfg && exec scrapyd-deploy"
    volumes_from:
      - test-static
    links:
      - test-scrapyd

  # we need the .local to allow session cookies to be used correctly by the
  # browsers/http libraries (like requests)
  test-web-e2e.local:
    extends:
      service: test-service_base
    command: gunicorn -b 0.0.0.0:5000 -t 3600 -w 1 --access-logfile "-" inspirehep.wsgi_with_coverage:application
    volumes_from:
      - test-static
    depends_on:
      test-database:
        condition: service_healthy
      test-indexer:
        condition: service_healthy
      test-rabbitmq:
        condition: service_healthy
      test-redis:
        condition: service_healthy
    environment:
      - APP_SERVER_NAME="test-web-e2e.local:5000"
      - APP_SESSON_COOKIE_DOMAIN=".local:5000"
      - APP_ARXIV_PDF_URL="/pdf/{arxiv_id}"
      - APP_ARXIV_PDF_URL_ALTERNATIVE="/pdf/{arxiv_id}"
      - APP_ARXIV_TARBALL_URL="/e-print/{arxiv_id}"
      - APP_PRODUCTION_MODE=True
      - APP_LEGACY_ROBOTUPLOAD_URL="http://fake-legacy:6666/"


  test-worker-e2e:
    extends:
      service: test-service_base
    command: celery worker -E -A inspirehep.celery_tests --loglevel=DEBUG --purge --queues celery,migrator,harvests,orcid_push
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD"
        - "bash"
        - "-c"
        - "/virtualenv/bin/celery --broker=pyamqp://guest:guest@test-rabbitmq:5672// inspect ping | grep OK"
    volumes_from:
      - test-static
    depends_on:
      test-database:
        condition: service_healthy
      test-indexer:
        condition: service_healthy
      test-rabbitmq:
        condition: service_healthy
      test-redis:
        condition: service_healthy
    environment:
      - APP_ARXIV_PDF_URL="http://fake-arxiv:8888/pdf/{arxiv_id}"
      - APP_ARXIV_PDF_URL_ALTERNATIVE="http://fake-arxiv:8888/pdf/{arxiv_id}"
      - APP_ARXIV_TARBALL_URL="http://fake-arxiv:8888/e-print/{arxiv_id}"
      - APP_PRODUCTION_MODE=True
      - APP_LEGACY_ROBOTUPLOAD_URL="http://fake-legacy:6666/"
      - APP_LEGACY_PID_PROVIDER="http://fake-legacy:6666//batchuploader/allocaterecord"

  e2e:
    extends:
      service: test-service_base
    command: py.test tests/e2e
    volumes_from:
      - test-static
    depends_on:
      test-database:
        condition: service_healthy
      test-indexer:
        condition: service_healthy
      test-rabbitmq:
        condition: service_healthy
      test-redis:
        condition: service_healthy
      test-worker-e2e:
        condition: service_started
      test-web-e2e.local:
        condition: service_started
      fake-arxiv:
        condition: service_started
      fake-legacy:
        condition: service_started
      test-scrapyd:
        condition: service_started
      test-scrapyd-deploy:
        condition: service_started
    environment:
      - APP_SERVER_NAME=test-web:5000
      - APP_CRAWLER_HOST_URL=http://test-scrapyd:6800
