version: '2'

services:
  service_base:
    # Overrides default inspirehep config.
    extends:
      file: services.yml
      service: base
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://inspirehep:dbpass123@database:5432/inspirehep
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=amqp://guest:guest@rabbitmq:5672//
      - CACHE_REDIS_URL=redis://redis:6379/0
      - SEARCH_ELASTIC_HOSTS=indexer

  # Services using the inspirehep code.
  web:
    extends:
      service: service_base
    command: inspirehep --debug run -h 0.0.0.0
    volumes_from:
      - static
    ports:
      - "5000:5000"
    links:
      - database
      - indexer
      - rabbitmq
      - redis
  worker:
    extends:
      service: service_base
    command: celery worker -E -A inspirehep.celery --loglevel=INFO --purge
    volumes_from:
      - static
    links:
      - database
      - indexer
      - rabbitmq
      - redis

  # Services needed for inspirehep to run.
  redis:
    image: redis
  indexer:
    extends:
      file: services.yml
      service: indexer
    ports:
      - "9200:9200"
    volumes:
      - "${DOCKER_DATA}/tmp/inspirehep_elastic/data:/usr/share/elasticsearch/data"
      - "${DOCKER_DATA}/tmp/inspirehep_elastic/log:/usr/share/elasticsearch/log"
  rabbitmq:
    image: rabbitmq
  database:
    extends:
      file: services.yml
      service: database
    volumes:
      - "${DOCKER_DATA}/tmp/inspirehep_db/data:/var/lib/postgresql/data/pgdata"

  # Services useful for monitoring/debugging.
  flower:
    extends:
      service: service_base
    ports:
      - "5555:5555"
    command: celery flower -A inspirehep.celery --broker=amqp://guest:guest@rabbitmq:5672//
    volumes_from:
      - static
    links:
      - database
      - indexer
      - rabbitmq
      - redis

  # Static volume config for service_base.
  static:
    extends:
      file: services.yml
      service: static
