version: '2'

services:
  base:
    image: inspirehep/python-base
  indexer:
    image: inspirehep/elasticsearch
    command: elasticsearch -Dcluster.name="inspire" -Ddiscovery.zen.ping.multicast.enabled=false
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=dbpass123
      - POSTGRES_USER=inspirehep
      - PGDATA=/var/lib/postgresql/data/pgdata
  static:
    image: busybox
    volumes:
        - ".:/code"
        - "${DOCKER_DATA}/tmp/virtualenv:/virtualenv"
